### PR TITLE
Make @webauthntine/browser work in node env

### LINKED ISSUE #6: @webauthn/browser not working with SSR
`@webauthn/browser` needs access to `window` when loading the module.
This causes errors in SSR environments, because window is not defined there.
Would be great if loading the module would also work in SSR environment.

### PR DESCRIPTION
**Pull request by P4sca1**
This is useful when `@webauthntine/browser` is used with SSR, e.g. using `nuxt.js` or `next.js`.

The first problem was that `window` is undefined in node which causes the `supportsWebauthn` method to throw an error trying to index undefined. This has been fixed by using typescript optional chaining.

The second problem is that the umd build is not working in node. This issue was discussed in https://github.com/webpack/webpack/issues/6784 and the solution is to use `output.globalObject: this` as also stated in [the docs](https://webpack.js.org/configuration/output/#outputglobalobject).

Closes #6

### CODE REVIEW

**Comment by P4sca1** [comment]
@MasterKale

File: packages/browser/src/helpers/supportsWebauthn.ts [hunk 1]
```diff
@@ -3,7 +3,7 @@
  */
 export default function supportsWebauthn(): boolean {
   return (
-    window.PublicKeyCredential !== undefined
+    window?.PublicKeyCredential !== undefined
```
Comment (MasterKale) [inline packages/browser/src/helpers/supportsWebauthn.ts:6]: Can you add a unit test to **supportsWebauthn.test.ts** for this please?

Comment (P4sca1) [reply packages/browser/src/helpers/supportsWebauthn.ts:6]: I added a test.

**Comment by P4sca1** [comment]
Btw would be great to use something like prettier or eslint styling rules to enforce a common coding style.

**Comment by MasterKale** [comment]
And yes, you're absolutely right about this project needing some code standards. I plan on adding at least Prettier formatting via `husky` and `lint-staged`, I just wasn't expecting collaborators so soon 🤗

**Comment by P4sca1** [comment]
I messed up the last commit. Could you remove the `if (global.window)` check in `setupTests.ts` again?

**Comment by MasterKale** [comment]
@P4sca1 Done and done, I ran the test suite and nothing adverse happened after removing it :v:

Also this fix has been published as **@webauthntine/browser@0.2.2**.
